# Generated by Django 3.2.15 on 2022-09-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.BigIntegerField(verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.PositiveSmallIntegerField(verbose_name='серия'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Prosrochena', 'Prosrochena')], default=('Active', 'Active'), max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], db_index=True, default=('F', 'F'), max_length=4, verbose_name='Пол'),
        ),
    ]
